# Generated by Django 3.1.3 on 2022-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('home', '0002_apppermissions'), ('home', '0003_auto_20220406_1047'), ('home', '0004_auto_20220406_1205')]

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_nextcloud', 'Can use Nextcloud'), ('use_codimd', 'Can use CodiMD'), ('use_dokuwiki', 'Can use dokuwiki'), ('use_hoover', 'Can use hoover'), ('use_rocketchat', 'Can use rocketchat'), ('use_hypothesis', 'Can use hypothesis')],
            },
        ),
    ]
