# Generated by Django 3.1.3 on 2022-03-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_nextcloud', 'Can use Nextcloud'), ('use_codimd', 'Can use CodiMD'), ('use_dokuwiki', 'Can use dokuwiki'), ('use_hoover', 'Can use hoover')],
            },
        ),
    ]
