# Generated by Django 3.1.3 on 2022-04-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_apppermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermissions',
            options={'permissions': [('use_nextcloud', 'Can use Nextcloud'), ('use_codimd', 'Can use CodiMD'), ('use_dokuwiki', 'Can use dokuwiki'), ('use_hoover', 'Can use hoover'), ('use_rocketchat', 'Can use rocketchat')]},
        ),
    ]
