# Generated by Django 3.1.3 on 2021-02-04 16:24

from django.db import migrations, models
import liquidcore.home.models


def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('home', 'Profile')
    for user in User.objects.all():
        p = Profile.objects.get_or_create(user=user)
        print(f'created profile {p.uuid} for user {user.username}')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=liquidcore.home.models.random_uuid, max_length=100),
        ),
        migrations.RunPython(forwards),
    ]
