# Generated by Django 3.1.3 on 2023-06-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230308_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermissions',
            options={'permissions': [('use_nextcloud', 'Can use Nextcloud'), ('use_nextcloud-instance-2', 'Can use Nextcloud Instance 2'), ('use_codimd', 'Can use CodiMD'), ('use_dokuwiki', 'Can use dokuwiki'), ('use_hoover', 'Can use hoover'), ('use_rocketchat', 'Can use rocketchat'), ('use_hypothesis', 'Can use hypothesis'), ('use_wikijs', 'Can use Wiki.js'), ('use_nextcloud26', 'Can use Nextcloud v26')]},
        ),
    ]
