# Generated by Django 3.2.20 on 2024-03-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_apppermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermissions',
            options={'permissions': [('use_nextcloud', 'Can use Nextcloud'), ('use_nextcloud-instance-2', 'Can use Nextcloud Instance 2'), ('use_codimd', 'Can use CodiMD'), ('use_dokuwiki', 'Can use dokuwiki'), ('use_hoover', 'Can use hoover'), ('use_rocketchat', 'Can use rocketchat'), ('use_hypothesis', 'Can use hypothesis'), ('use_wikijs', 'Can use Wiki.js'), ('use_nextcloud28', 'Can use Nextcloud 28'), ('use_grist', 'Can use Grist worksheets')]},
        ),
    ]
