# #########################################################
#                       TEST
# #########################################################
kind: pipeline
name: test

steps:
- name: flake8
  image: alpine/flake8:6.0.0
  commands:
  - flake8

- name: test
  image: python:3.11-bullseye
  commands:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends qrencode
  - pip install flake8 pipenv > /dev/null
  - pipenv install --system --deploy --ignore-pipfile
  - pytest --forked

---
# #########################################################
#                       BUILD x86
# #########################################################
kind: pipeline
name: build x86

trigger:
  status:
  - success
  event:
  - push
  - tag
  - cron

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/core
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    branch:
      exclude:
      - dependabot/**

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/core
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
# #########################################################
#                       BUILD arm64
# #########################################################
kind: pipeline
name: build arm64

platform:
  os: linux
  arch: arm64

trigger:
  status:
  - success
  event:
  - push
  - tag
  - cron

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/core
    tags: ${DRONE_COMMIT_BRANCH}-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    branch:
      exclude:
      - dependabot/**

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/core
    auto_tag: true
    auto_tag_suffix: arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
# #########################################################
#                   build multiplatform
# #########################################################

kind: pipeline
name: build multiplatform

depends_on:
- build x86
- build arm64

clone:
  disable: true


steps:
- name: docker multiplatform branch
  image: docker
  pull: if-not-exists
  environment:
    IMG: "liquidinvestigations/core:${DRONE_COMMIT_BRANCH}"
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
  - "docker buildx imagetools  create --append $IMG --append $IMG-arm64 --tag  $IMG"
  when:
    event:
    - push
    - cron

- name: docker multiplatform tag
  image: docker
  pull: if-not-exists
  environment:
    IMG: "liquidinvestigations/core:${DRONE_TAG:1}"
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
  - "docker buildx imagetools  create --append $IMG --append $IMG-arm64 --tag  $IMG"
  when:
    event:
    - tag
---

# #########################################################
#                       SECRETS
# #########################################################
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
