# Generated by Django 3.1.3 on 2021-06-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0002_auto_20190420_0723'),
        ('twofactor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDeviceTimed',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.totpdevice')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_totp.totpdevice',),
        ),
    ]
