# Generated by Django 3.1.3 on 2023-01-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twofactor', '0002_totpdevicetimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twofactor.totpdevicetimed'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='opened_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
