# Generated by Django 3.1.3 on 2023-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('twofactor', '0003_invitation_state'), ('twofactor', '0004_auto_20230120_1310')]

    dependencies = [
        ('twofactor', '0002_totpdevicetimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='state',
            field=models.CharField(choices=[('valid', 'valid'), ('used', 'used'), ('expired', 'expired')], default='valid', max_length=200),
        ),
    ]
