# Generated by Django 3.1.3 on 2023-01-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofactor', '0002_totpdevicetimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='opened_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
