# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField()),
                ('state', models.CharField(blank=True, max_length=30)),
                ('state_description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data_text', models.TextField()),
            ],
        ),
    ]
