# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 16:12
from __future__ import unicode_literals

from django.db import migrations

def create_service_instances(apps, schema_editor):
    Service = apps.get_model("config", "Service")
    service_list = [
        {'name': 'hoover', 'is_enabled': True},
        {'name': 'hypothesis', 'is_enabled': False},
        {'name': 'matrix', 'is_enabled': False},
        {'name': 'dokuwiki', 'is_enabled': True},
        {'name': 'davros', 'is_enabled': True},
    ]

    for kwargs in service_list:
        service = Service(**kwargs)
        service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_service_instances)
    ]
