# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 16:12
from __future__ import unicode_literals

from django.db import migrations

def create_service_instances(apps, schema_editor):
    Service = apps.get_model("config", "Service")
    service_name_list = [
        'hoover',
        'hypothesis',
        'matrix',
        'dokuwiki',
        'davros',
    ]

    for name in service_name_list:
        service = Service(name=name, is_enabled=True)
        service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_service_instances)
    ]
