# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0004_auto_20171011_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNClientKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(editable=False, max_length=255)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.CharField(max_length=255, null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
