# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 21:18
from __future__ import unicode_literals

import json
from django.db import migrations

def create_vpn_setting_instance(apps, schema_editor):
    Setting = apps.get_model("config", "Setting")
    vpn_default = {
        "server": {
            "is_enabled": False,
            "error_message": None,
        },
        "client": {
            "is_enabled": False,
            "error_message": None,
        }
    }
    Setting(name='vpn', data_text=json.dumps(vpn_default)).save()

class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_vpnclientkey'),
    ]

    operations = [
        migrations.RunPython(create_vpn_setting_instance),
    ]
