# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20171025_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnclientkey',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vpnclientkey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vpnclientkey',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vpnclientkey',
            name='revoked_reason',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
