# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 12:49
from __future__ import unicode_literals

import json
from django.db import migrations


def create_vpn_client_config(apps, schema_editor):
    Setting = apps.get_model("config", "Setting")
    Setting(name='vpn_client_config', data_text=json.dumps(None)).save()


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20171027_1006'),
    ]

    operations = [
        migrations.RunPython(create_vpn_client_config),
    ]
