# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 19:34
from __future__ import unicode_literals

import json
from django.db import migrations


def create_vpn_server_address(apps, schema_editor):
    Setting = apps.get_model("config", "Setting")
    vpn_setting = Setting.objects.get(name='vpn')
    vpn = json.loads(vpn_setting.data_text)
    vpn['server']['address'] = {'address': '127.0.0.1', 'port': '1194'}
    vpn_setting.data_text = json.dumps(vpn)
    vpn_setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20171027_1249'),
    ]

    operations = [
        migrations.RunPython(create_vpn_server_address),
    ]
