# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_service_instances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trusted', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=50)),
                ('data_text', models.TextField()),
            ],
        ),
    ]
